"""Stable value objects shared by the query runtime and its adapters."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum
from types import MappingProxyType
from typing import Any, Mapping


class RuntimeMode(StrEnum):
    """How the modular runtime participates in one query turn."""

    LEGACY = "legacy"
    SHADOW = "shadow"
    AGENT = "agent"


def _frozen_mapping(value: Mapping[str, Any] | None) -> Mapping[str, Any]:
    return MappingProxyType(dict(value or {}))


@dataclass(frozen=True, slots=True)
class IdentityContext:
    """Authenticated enterprise identity; never inferred from prompt text."""

    user_id: str
    username: str
    roles: tuple[str, ...] = ()
    department_id: str | None = None
    organization_scope: tuple[str, ...] = ()
    permissions: tuple[str, ...] = ()

    def __post_init__(self) -> None:
        if not self.user_id.strip() or not self.username.strip():
            raise ValueError("authenticated user_id and username are required")


@dataclass(frozen=True, slots=True)
class SessionContext:
    """Query-only session boundary.

    ``product`` is deliberately fixed to ``query`` so a Q&A session cannot be
    accidentally replayed by the data agent.
    """

    session_id: str
    correlation_id: str
    product: str = "query"
    conversation_id: str | None = None

    def __post_init__(self) -> None:
        if not self.session_id.strip() or not self.correlation_id.strip():
            raise ValueError("session_id and correlation_id are required")
        if self.product != "query":
            raise ValueError("query runtime only accepts product='query'")


@dataclass(frozen=True, slots=True)
class QueryRequest:
    """One normalized request entering the query runtime."""

    text: str
    identity: IdentityContext
    session: SessionContext
    metadata: Mapping[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not self.text.strip():
            raise ValueError("query text cannot be empty")
        object.__setattr__(self, "metadata", _frozen_mapping(self.metadata))


@dataclass(frozen=True, slots=True)
class QueryPlan:
    """Auditable plan generated by the planner."""

    intent: str
    steps: tuple[str, ...]
    required_permissions: tuple[str, ...] = ()
    parameters: Mapping[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not self.intent.strip() or not self.steps:
            raise ValueError("query plan requires an intent and at least one step")
        object.__setattr__(self, "parameters", _frozen_mapping(self.parameters))


@dataclass(frozen=True, slots=True)
class ToolResult:
    """Result produced by one registered Skill/tool."""

    tool_name: str
    payload: Any
    success: bool = True
    error: str | None = None
    metadata: Mapping[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not self.tool_name.strip():
            raise ValueError("tool_name is required")
        object.__setattr__(self, "metadata", _frozen_mapping(self.metadata))


@dataclass(frozen=True, slots=True)
class ValidatedResult:
    """Execution output after permission, data, and business validation."""

    results: tuple[ToolResult, ...]
    valid: bool
    issues: tuple[str, ...] = ()
    facts: Mapping[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        object.__setattr__(self, "facts", _frozen_mapping(self.facts))


@dataclass(frozen=True, slots=True)
class QueryResponse:
    """Runtime-neutral response returned to the existing HBJTBOT adapter."""

    payload: Any
    mode: RuntimeMode
    correlation_id: str
    trace_id: str
    fallback_used: bool = False
    metadata: Mapping[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        object.__setattr__(self, "metadata", _frozen_mapping(self.metadata))
