[package]
name = "mes-desktop"
version = "0.1.0"
description = "MES Digital Twin desktop application"
authors = ["赵丞"]
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "mes_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[features]
custom-protocol = ["tauri/custom-protocol"]
